### ISSUE TITLE
Cant do my own Al

### ISSUE THREAD

**Issue by Hextr2** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#1040]
Hi I tried  to do better rat so I check some videos how to do it and wanted to improve rat but when I tried to install it into unofficial crusader patch this error code shows up  (
Error loading AIC files: C:\Program Files
(x86)\Steam\steamapps\common\Stronghold Crusader
Extreme\Unofficial CrusaderPatch_2.15b\resources\aic\myrat.json )
any help why it doesnt work ? 
TY

**Comment by gynt** [comment]
@Hextr2 Are you sure your JSON is correctly formatted and specified?

**Comment by Hextr2** [comment]
ty but I already found the problem, I wrote Slaves in code and it should be only Slave xd
