### ISSUE TITLE
The gane does not run I have latest version from steam 1.41 and does not run, aob stuff shows, also why on earth it download 450 mb file every time I change the folder

### ISSUE THREAD

**Issue by Abdo95134** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#25]
**Describe the bug**
A clear and concise description of what the bug in the game is. Including whether the bug exists in the vanilla game or whether the bug exists because of a mod.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Save game**
Share your .sav or .msv file (save game) before the bug occurs and after the bug has occurred, if possible.

**Desktop (please complete the following information):**
 - Version of the game [e.g. 1.41]
 - Version of the UCP modding framework
 - Version of the UCP GUI

**Additional context**

**Comment by gynt** [comment]
We fixed this issue over Discord. Although you didn't give confirmation what the issue was, it likely was the fact you used a language other than one of the supported latin languages
