### ISSUE TITLE
Araber Truppe Meuchelmörder bug 

### ISSUE THREAD

**Issue by JuliusderZerstoerer** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#33]
Hi ich habe einen Fehler im Spiel gefunden und zwar geht es um die Araber Truppe Meuchelmörder und zwar wenn die Leute angreifen wollen bleiben die einfach stehen und tuen nichts das gleich auch wenn die eine Mauer/Torhaus anklickt wollen die wo anders hoch als da wo man möchte. Ich hoffe, man kann den Fehler beheben.

**Comment by gynt** [comment]
Duplicate of https://github.com/UnofficialCrusaderPatch/UnofficialCrusaderPatch/issues/32
