### ISSUE TITLE
New AIV files created

### ISSUE THREAD

**Issue by FAPLZ** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#649]
Hello

I created for any AI new AIV files and I want to share it and add it to the patch.

**Comment by GRhin** [comment]
Hi faplz,
Most of the team dont want to include any new custom content with the patch
as it would get unmanageably large. You can share your aivs on stronghold
heaven. I hope to one day have time to create my own place for these mods
to be stored and shared, but I suspect that's a long way off yet.

**Comment by FAPLZ** [comment]
ok, but thank you for answering

**Comment by Russianstory** [comment]
@FAPLZ  I would be grateful if at least here you can post screenshots of your fortresses ... just so that we can see ... what they are. =)

**Comment by FAPLZ** [comment]
you can watch all pictures at: https://github.com/FAPLZ/AIV-files-for-Stronghold-Crusader

**Comment by Lolasik011** [comment]
@FAPLZ  Thank you !

**Comment by Russianstory** [comment]
@FAPLZ are you doing from scratch? I have somewhere the best, in my opinion, the fortresses of all the lords .. I could throw them to you - you would suddenly look like you suddenly want to remake. These files were all downloaded from Heavengames

**Comment by FAPLZ** [comment]
@Russianstory 

yes i created all castles from scratch and i used the original castles (more or less) as a model

**Comment by Russianstory** [comment]
@FAPLZ I would really like to get new, really NEW and really STRONG serious fortresses of all the lords At least the first campaign! I'm playing with those now. which were in the UCP patch ... but I want even stronger, but at the same time, well-executed locks. So that on the  maps they look normal.

**Comment by Lolasik011** [comment]
> @FAPLZ I would really like to get new, really NEW and really STRONG serious fortresses of all the lords At least the first campaign! I'm playing with those now. which were in the UCP patch ... but I want even stronger, but at the same time, well-executed locks. So that on the maps they look normal.

It's very difficult to implement. I'd like that, too.

**Comment by FAPLZ** [comment]
@Russianstory should i create more castles with these criteria?
And what do you mean with new? ;do you mean a another structure of the castles?

btw, the files i created are new (obviously) and the castles are also very strong (more or less, according to the lord)
i tested all by myself and AI vs AI, for a long time and a lot of matches.

You can also download all files on heavengames (http://stronghold.heavengames.com/downloads/showfile.php?fileid=8495)

**Comment by Russianstory** [comment]
@FAPLZ I had something else in mind. I have collected files of fortresses that I downloaded from the site a long time ago. I personally chose those files that are the strongest powerful ... well, strong. and improved them a little ..... I thought I was going to find them and throw them to you .... suddenly you like them and you fix them or modify them ... I just see you will have a great job ... but I have I have my own vision .... for example, I would strengthen the Rat and the Snake well ... I just have such locks ... I really liked them .... I can find and share.

**Comment by FAPLZ** [comment]
@Russianstory 
yes i like to watch for your aiv files.
where i can get them?

**Comment by Russianstory** [comment]
Here in the archive are all AIV files of all Bots ... I downloaded a lot of files of all fortresses of all bots from the Heavenjames website. PROBABLY you may not even recognize some of them ... I downloaded them ... then I myself checked and selected those that I liked the most. Then I added them separately and then personally through the program I added dogs, ballistas, towers, mangonels, tar ditches and wolf pits ... Especially wolf pits inside the castle. It is very powerful and effective. I was convinced myself. BUT since the wonderful USP 2.14 patch came out and I also found out that you can and love to work with AIV, I thought maybe somehow I could fix the horror that I did with them ... but at the same time we improved their layout and strengthened them to the maximum .. For example, there are excellent snake and rat castles. =) I would be very happy if you help me)) If not, then it's okay =))))

https://mega.dp.ua/ru/3v4PaMN

**Comment by FAPLZ** [comment]
ok, i can look for these castles.
I'll catch up later

**Comment by Russianstory** [comment]
How did you manage to watch the AIV?

**Comment by FAPLZ** [comment]
i just use your link and downloaded it

**Comment by Russianstory** [comment]
OK good. I'll be glad to hear and see your ideas, advice, opinions and if it turns out, maybe even modified types of fortresses =).

**Comment by Russianstory** [comment]
And how ?))))))))

**Comment by Russianstory** [comment]
@FAPLZ Well, what do you think about these varinats?

**Comment by FAPLZ** [comment]
@Russianstory 
indeed, i would say that the castles are good as they are and i wouldnt change anything.
except you really want that the castles get a change.
then i can do this, but this take a long time...

**Comment by Russianstory** [comment]
@FAPLZ 
Buddy! I would be very glad if you would improve the fortresses. If it is possible. I tried there... but then quit.... A lot of incomprehensible stuff.
All I wanted to do was:

1) Make a MAXIMUM of wolf stakes both behind the fortress and inside
2) Now after the patch UCP so that all the Bots have built on the 3 apts on the perimeter
3) That the tower (mangonel and ballista) and ground (trebuchet and ballista) siege weapons were as much as possible. 
4) All bots should have cages with dogs
5) Fortresses should be very heavily fortified.
6) Weak Bots to strengthen as much as possible (Rat, Serpent, Sultan) 

Translated with www.DeepL.com/Translator (free version)

**Comment by FAPLZ** [comment]
all right, i willl see what i can do.
but for 128 AIV files, that will take a lot of time

**Comment by Russianstory** [comment]
My friend, I am ready to wait. Himself all the time in the waiting process. I am finishing my mod slowly.

**Comment by Russianstory** [comment]
I remember there seems to be the Snake has a cool compact strong fortress. Straight and siege weapons and walls, plus new AI and tactics ... it will be generally super!

**Comment by FAPLZ** [comment]
@Russianstory 

i'm finished with the castles of the abbot.
if you want to take a look at the castles, follow these link: https://github.com/FAPLZ/AIV-files_Test
The other AIV files will be processed next.

**Comment by Russianstory** [comment]
@FAPLZ  Greetings my friend! Thank you very much! I will definitely look but on Saturday .... I will play and then I will share my emotions! Thank you!

**Comment by Russianstory** [comment]
What abour other AIVS ?))

**Comment by FAPLZ** [comment]
@Russianstory 
The other AIV files are coming soon, i dont have the time to edit it everyday...

**Comment by Russianstory** [comment]
@FAPLZ Hello my friend, how are you doing)

**Comment by FAPLZ** [comment]
@Russianstory 
Hello
I am ready and finished the last AIV files, but i want to test all files before.
If you want to take a preview, you can download all files here: https://github.com/FAPLZ/Russianstory_AIV_files_modded

Sorry, that it takes so long to edit the files, but some files are very difficulty to edit :)

**Comment by Russianstory** [comment]
@FAPLZ  What are you, my friend, I'm ready to wait as long as necessary. I am not rushing you. I am very grateful to you for the help you have given me! I just wondered what else there is?)) Thank you very much. Do it and don't rush, I'm in no hurry. Thank you =)

**Comment by FAPLZ** [comment]
@Russianstory Your AIV files are ready yet (https://github.com/FAPLZ/Russianstory_AIV_files_modded)
if you find any mistakes, then tell me and i will fix it

**Comment by Russianstory** [comment]
XCELLENT my dear friend! Thank you, I will play with them and write a review =)

**Comment by Russianstory** [comment]
Hello my friend. The castles are great! Tell me, is it possible to put locks for four pharmacies? Since in the new patch, the pharmacist now has a log unit. He can heal units. And if you can lay wolf stakes to the maximum and inside the castle along the perimeter of the castle. Place dog cages and siege weapons in front of castle walls where there are none?

**Comment by Russianstory** [comment]
@FAPLZ It seems to me that given the fact that the PATCH has the ability to heal units, it will be great if the computer BOTS can put pharmacies (2-4 buildings) in their fortress to heal wounded units and the lord himself. It seems to me that this is the correct process, which is interesting and complicating the game.

**Comment by FAPLZ** [comment]
Hi @Russianstory 

sure, i can change the files, that every AI have a medic
i will start right now

**Comment by Russianstory** [comment]
Hi @FAPLZ  friend
And in addition to pharmacies, can you also increase the number of stakes from the ground, and cages with dogs and siege weapons in front of castles and on towers? stakes from the ground, if possible, both inside the fortress and outside to the maximum. PLEASE =)

**Comment by FAPLZ** [comment]
yes i can increase it.
But  you have to know, that a AI only build 10 dog cages, doesnt matter, if you place more then 10 in the AIV file and a castle shoud not have more then 999 steps to build, because when its more then 999 errors can occur.

But i will see, what i can do.

**Comment by Russianstory** [comment]
Yes, yes, of course, I know about it. I just want to somehow increase the amount to the maximum. Especially if there are a lot of wolf stakes both near the fortress and inside, it will be great. Well, about pharmacies, and so everything is clear =)

**Comment by FAPLZ** [comment]
all right, i change the things and I'll get in touch

**Comment by FAPLZ** [comment]
@Russianstory 

i am ready.
take a look: https://github.com/FAPLZ/Russianstory_AIV_files_modded

**Comment by Russianstory** [comment]
OK, I understood you, thank you, I'll play and say =) THANK YOU

**Comment by Russianstory** [comment]
@FAPLZ Hello, I'm playing with these fortresses right now. Tell me, did you not make an appetite for the Snake, the Rat, the Boar, the Sultan, the Khalifa?

**Comment by FAPLZ** [comment]
I analyzed the files of caliph, rat, pig, snake and sultan.
what exactly is the problem? Is it, that they dont build the fire ballists or the dog cages?
because actually it shouldnt be the same files like before...
strange thing

**Comment by Russianstory** [comment]
You see, I'm more worried about the lack of pharmacies at the Rat, Snake, Boar, Sultan, Khalifa, Wolk, Richard, Saladin, and others. I meant pharmacies =) They are not in these files .... How can I add? Can you please add?

**Comment by FAPLZ** [comment]
i see the problem, i will change it and call you back

**Comment by FAPLZ** [comment]
all right, i think now it should work...
https://github.com/FAPLZ/Russianstory_AIV_files_modded

**Comment by Russianstory** [comment]
Do Bots already have pharmacies here ??

**Comment by Russianstory** [comment]
Better now. But Serpent doesn't build pharmacies ... Rat has 2 pieces, Sultan has 4 pieces. This is great. I beg you again, can you add 5 pharmacies to each Bot for each fortress? I would be very grateful? I'll just do AIC later to these fortresses and ask a person to make AIC under my fortresses

**Comment by FAPLZ** [comment]
sure, i change it so every ai has 5 pharmacies and why snake dont build it

**Comment by Russianstory** [comment]
I will then play with all the Serpents, and go to all the fortresses in a long period of time. Maybe there is some delay in the construction of pharmacies

**Comment by Russianstory** [comment]
I played, looked - none of the Snakes builds pharmacies. Very strange. I play on the same map with all the fortresses of the Serpent Lord

**Comment by FAPLZ** [comment]
i will inform me, why it doesnt work
thats really strange....

**Comment by Russianstory** [comment]
Ye it so strange maybe they cannot to build ? Tell me, are they building wolf pits Rat, Serpent, Sultan, Boar, Caliph? I'm testing the Snake while

**Comment by Russianstory** [comment]
@FAPLZ Tell me, are wolf stakes all made to the maximum or not?

**Comment by FAPLZ** [comment]
yes, there are in every AIV file: 10 dog cages

**Comment by Russianstory** [comment]
@FAPLZ Hello my friend. Please tell me if I want to add more wolf stakes to the fortress myself. Can I add them simply by entering the program? There is a countdown in the order of all buildings.

**Comment by Russianstory** [comment]
Plz teach me how to use AIVeditor and Downloand My AIVs  i wanna to add more killing pits

**Comment by FAPLZ** [comment]
@Russianstory 3 Things:

first: i am finished your AIV files (https://github.com/FAPLZ/Russianstory_AIV_files_modded), all AIV files have 5 Healers now, but i saw that some Lords are buildung Walls very strange (I will fix it later)

second: i added one time more then 10 dog cages in a AIV file, but the AI builds only 10 dog cages (this cannot be changed via UCP now)

third: i can help you with the AIV program and dowload your AIV files
The AIV program (called: village.exe) can you download here:

http://stronghold.heavengames.com/downloads/showfile.php?fileid=7534&ci=f7eec75a219e7588d9853debef964809YToxOntpOjA7YToyOntpOjA7czoxNDoiU2VhcmNoIFJlc3VsdHMiO2k6MTtzOjM2OiJsaXN0ZXIucGhwP3N0YXJ0PTAmYW1wO3NlYXJjaD1lZGl0b3IiO319

following informations are not important yet, but good to know:
If you use the AIV editor, there are some bugs and problems, like if you want to put a break in the building progress of the AIV file and want to delete it, then the AIV editor crashes.
Or if you put more then 1000 to 1200 steps in the file, then the AI build these strange walls (like discripted above).
if you do more then 1200 steps into the file, then the file probably doesnt work in the game.

if you have more questions, then i can help you. just ask me

**Comment by Russianstory** [comment]
Thank you very much for your help!
Yes, I just wanted to finish killing pits to the maximum amount. Especially inside the fortress, fill in all free cells. And the Editor doesn't work. I put our files in the villages folder, NEXT went to the Villages shortcut and there are these files, but they are all the same. 
![image](https://user-images.githubusercontent.com/48765277/122663970-12cb7780-d1a7-11eb-8b8d-33ee9405b564.png)

**Comment by Russianstory** [comment]
It makes even more sense in a large number of killing pits. They are very good at protecting the fortress when an assault is underway. If there was such an opportunity, then I would fill each fortress with these killing pits and make the maximum inside the fortress too =) =)

**Comment by FAPLZ** [comment]
ok, i understand
but what do you mean with all files are the same?
maybe you can try it if you create a ne test file and compare it with the files that doesnt work.

**Comment by Russianstory** [comment]
Yes, I came in with administrator rights. Nothing changes. I meant that all the Rat files, all 8 pieces in my program are loaded in the form of the same Csatle (AIV fortress)

**Comment by FAPLZ** [comment]
maybe the files are corrupt
you can try to download the original files again (https://github.com/FAPLZ/AIV-files-for-Stronghold-Crusader) and put them into the folder "villages"
if it doesnt work either, then you i can look waht the problem is. but i didnt had the problem, that all the files are the same

maybe i find an solution...

**Comment by Russianstory** [comment]
Look, I put your new @Backup files in the Villages folder and everything started working fine as it should. THIS is all the original old fortresses are originals. But, my AIV, which you made with the latest and most recent changes, the AIVEditor program could not see. All the fortresses were the same.

**Comment by FAPLZ** [comment]
does the AI build in the game all castles or only these you see in the editor?

**Comment by Russianstory** [comment]
all castles like as usual

**Comment by Russianstory** [comment]
So. I re-installed everything and re-downloaded all files. Now everything seems to be working correctly. =) But there, in each file, there seems to be a limit of buildings =) so you can no longer put stakes. Moreover, there in the game it seems that not everywhere BOTS put these stakes, can the limit on the number of objects affect?
And also ... I realized what strange walls we are talking about =)

**Comment by FAPLZ** [comment]
@Russianstory 

i am back now. did everything worked correctly now? I tested it with a lot of more stakes but mostly the game chrashed or the AIV isn't builded right.

**Comment by Russianstory** [comment]
@FAPLZ  Hello friend!)) I also watched the game ... but I don't understand what exactly you are talking about? What's wrong with the files? I played with them, but the problem is different - there is no special AIC on my AIV

**Comment by FAPLZ** [comment]
a AIC can you only install with the UCP (Unofficial crusader patch). I tested it; if you put, in the village.exe for example a slinger on a wall in the AIV file of a castle from the pig, then the AI doesnt create the slinger unit, because it isnt discripted in the AIC.
It is a bit difficult to understand if i only discripe it.
the best thing to learn is to test and play with the village.exe and look in tronghold crusader if it work and what work or what not  work.

**Comment by Russianstory** [comment]
Understood. But I thought that the best option would be if a new special AIС was created for my AIV

**Comment by FAPLZ** [comment]
no problem, you can also do it by your own.
just take a vanilla AIC and script it so, that it fits to your AIVs

**Comment by FAPLZ** [comment]
Hello @Russianstory
I think these are the last created files from you; link: https://github.com/FAPLZ/Russianstory_AIV_files_modded

if not then just tell me

**Comment by Russianstory** [comment]
@FAPLZ  HI WAZZUP BRO =)!!!!!!!!!!!!!!

**Comment by FAPLZ** [comment]
@Russianstory Hello :)

**Comment by Russianstory** [comment]
How are you doing modding the game? What new interesting thing happened to do?)

**Comment by Russianstory** [comment]
@FAPLZ Listen, bro, and our Rat, Snake and Pig make pikemen. The pig even hires them a little. But the Rat and the Serpent only spend space, money and time on them. Can you please remove Rat and Snake workshops and add spearmen and archers workshops instead?

**Comment by Russianstory** [comment]
@FAPLZ HELLO I can ask you to finish some old Fortresses and I also found a few replacement fortresses. I would also very much ask you to strengthen them, like our previous ones, and pharmacies and wolf stakes and fire, and mangonels with ballistas and more dogs. Please help, friend?

**Comment by FAPLZ** [comment]
@Russianstory 
Hello my friend, sorry i totally forget you. i previously wrote another script for a mod and doesnt worked on stronghold.
i can look what i can do to help you.

**Comment by Russianstory** [comment]
This sounds promising! =)

Yes, the point is that our Rat, Snake and Pig make pikemen. The pig even hires them a little. But the Rat and the Serpent only spend space, money and time on them. Can you remove the workshops for the production of pikemen in armor from the Rat, the Snake, the Boar? The production of Pike (halberds) and iron armor slows down the development of the economy and the speed of recruiting an army from them.
And also, if it is possible and you will be interested - to fill the free space in the fortresses of the bots with the necessary buildings ... maybe other workshops, or wolf stakes and at our fortresses, which we did (I only play in them) and those fortresses that I selected today (there are a few pieces of 15). By the way, it is a pity that the limit on wolf stakes has not been removed ((.

p.s.
1) What fortresses do you play?
2) Are there very strong strong fortresses stronger than mine?
3) Can you please further improve the position of buildings and objects near my fortresses namely (Rat, Wolf, Boar, Serpent, Richard, Saladin, Caliph, Sultan, Nizar, Emir, Wazir). Add the maximum number of stakes, and fire ditches.

p.p.s
Can you remove the bad things that demoralize the armies of the Wolf and Caliph. May their armies be stronger.

Do you work with AI? I mean army recruitment speed, attack waves, types of units?

**Comment by FAPLZ** [comment]
@Russianstory 

i understand. i can change the castles like you want it.

to your questions:

1. i mainly play with my own created castles (AIV) and with my own AIC. but i also like to play it with vanilla AIVs and AICs from the unoffical patch.
2.  i think my AIVs are very strong but not invincible (for example one castle from the rat have no more then 2 big towers with ballists so it can be that other rat castles with 8 ore more towers are pretty stronger then mine. But the Wolf castles are more powerfull then the vanilla ones).
3. i can take a look what i can do
4. i can also remove the bad things in wolf and caliph castles and so on
5. i mean with "wrote another script for a mod", that i currently working on a mod for an another game. not stronghold. 

then i have some questions for you:

1. do you use the vanilla AIC or do you use a modified AIC
2. What AIV files do you use currently? are they the castle files that i send you last time?

**Comment by Russianstory** [comment]
@FAPLZ 
1) I'm using a modified AIC, don't remember which one. In my opinion, which came with UCP 2.1.5b
2) Yes, these are the AIV files that I sent you for revision, remember (pharmacies, stakes inside the fortress, dogs for everyone ...), then I tested them, then we finished them better. And now I tested them and realized that the fortresses themselves are good (although not all of them), but the layout inside the fortress leaves much to be desired (this is more a question for the authors of these fortresses). Some of them do not make their weapons, though units are hired, but 10 pikemen from a Rat or a Boar do not make them strong. It is better to fill the entire space with either houses or workshops. And where you can’t put a building, it’s very cool to make more wolf stakes.
Also, it would be great if you could make an excellent complex AIC for these fortresses. And if it is possible to make fortresses impregnable for assassins.

https://disk.yandex.ru/d/Lq7PIuBLznqFSA

https://disk.yandex.ru/d/ncfbwSMR-lhl2w

Please help me my ally

**Comment by Russianstory** [comment]
@FAPLZ Or if you can not download, then tell me where you can download the files?

**Comment by FAPLZ** [comment]
@Russianstory hello my friend

Your answers help me a lot.
i will work on it.
In the next time i will be very busy.
so i write you soon in the next time and tell you what i did.

**Comment by Russianstory** [comment]
@FAPLZ Hi friend!! =)
And your help helps me a lot in turn! Thank you very much! =) There are two archives and all files. I will be glad for any help. I would like these fortresses to become stronger and stronger and more compact BUT WITHOUT removing buildings and WITHOUT reducing their size. The only thing you want to do is remove the BAD THINGS from the Bots so that their armies become stronger or even if it would be good to add Good things so that the armies become stronger. =)

**Comment by Russianstory** [comment]
@FAPLZ And please tell me when to expect you - in a month or two, or maybe in August?

**Comment by Russianstory** [comment]
@FAPLZ 
Greetings sir! =)
Huge gratitude! =)
I got you. Is it possible to simply remove the workshops for pikemen and armor and instead make more workshops for archers, spearmen and leather armor? I just would like if it is possible to somehow make the fortresses more compact WITHOUT REDUCING their existing size. And also just to strengthen their army where possible. And I also ask you very much if you can remove these separate pieces of walls that the AI builds.

And the question is - is it possible to add even more spikes inside and outside the fortress?

What else do you think can be done to improve these fortresses in terms of defense and quickly hire large armies, precisely in the context of the fortress (buildings, production)

**Comment by FAPLZ** [comment]
@Russianstory 

Yes the separate pieces of walls which the ai build is a big problem and i am not 100% sure, why the ai does it.
i tested it and mostly it happens when the castle size (aiv size) in the editor is larger then 999 builds (for example some castles of saladin have more then 1000 steps to build.)
And when a aiv have more then 999 steps to build then the ai do this random wall placement.
this is also the problem, that i cant make the castle even bigger, i think.

Second idea was that the ai want to build some walls at an existing block, like a pitch block or water or maybe also out of the map and then the ai build the wall in the opposit site of the map.

I will test it why the ai do this and make the aiv files so that it wont happen.

**Comment by Russianstory** [comment]
@FAPLZ 
I got you! I really hope that the fortresses will become even stronger and less vulnerable.

And the question is - there I threw another archivist with new fortresses ... a small one. Have you watched them?

**Comment by FAPLZ** [comment]
@Russianstory 

Hello my friend

I have some good and some bad news for you.

The good news are, that the separate walls that the ai build, are not the problem of the AIV files. it is more the position of the castle on the map which makes the problem. also i have finished most of the aiv from you.
the bad news are, that i still not know to 100% why the ai builds these separate walls.

To make the castles less vulnerable, ican place in the AIV Editor on every empty field a spike trap if you want that, but i dont know if this makes sense, also to replace armorer and poleturner with tanner and fletcher (also the poleturner produces pikes and / or spears). please tell me if you really want to replace them. it is no problem to do so.

**Comment by Russianstory** [comment]
@FAPLZ And as for the good things.
I wanted all Bots to have only good things just because it strengthens their armies. becomes a little more difficult to play =). If you can do good things without much damage to their economies, so that the army of the camp will be even stronger?

Some fortresses have a lot of statues and gardens. Maybe you can remove a number of statues, but so that the morale also remains maximum. And can all these statues be placed more compactly next to the fortresses, so that it is both compact and does not take up much space? =)

**Comment by Russianstory** [comment]
@FAPLZ You know what I'll tell you. Having been playing this game for a very long time, I realized that it is possible to improve the defense of fortresses even more. Since I like to play assassins very often, these assassins cut everyone and everything before climbing the wall. And I noticed that the assassins take a very long time to break trebuchets. I mean, they spend a lot of time on the trebuchets that get in their way!

**Comment by FAPLZ** [comment]
@Russianstory 

All right, i will see what i can do. Now i know how i can improve the castles.
i tell you when i am ready :)

**Comment by Russianstory** [comment]
@FAPLZ Great! =) Thank you very much!
I really noticed this in relation to the assassins and trebuchets. But maybe the rest of the sieged weapons and units also "combine" in the same way =)

**Comment by FAPLZ** [comment]
@Russianstory 

Hello my friend
i am making progress with the castles and i also watched your created castles you send me:
(НЕСКОЛЬКО НОВЫХ ИИ ДЛЯ SC1 SOME NEW AI FOR SC1ОТ 26.03.2023 and NEW ERA 128AIV 28.03.2023).

These are very cool castels. for example i very like the wolf and phillip castles you created.

In the meantime when i edit the aivs, you can test my aiv castles with the matching aic i created if you want. i think then the ai is stronger then in vanilla, but not so strong like the castles you use. if you want to test it anyway just tell me

i write you soon :)

**Comment by Russianstory** [comment]
@ Greetings my dear friend!

THERE was the first batch where there were all the fortresses 128 pieces, I threw you for reinforcement =)
And then yes there was a new set of only some AIVs. These are all fortresses not made by me. I only found them in the intrent, tested them, chose the best ones in my opinion and then played further to understand their pros and cons. And this little batch of fortresses is also the same. I found them, chose the best strong fortresses and wanted to improve the game process with them.
Yes you can try =)

**Comment by FAPLZ** [comment]
@Russianstory 

Yes i see the castles and these are really very good.
If you want to test my castles here is the link:

https://drive.google.com/drive/folders/1q48gzPgI33qvyqesLG1VpZ7pOWDcz6L5?usp=sharing
https://drive.google.com/file/d/1F-QGg0xX2XYn7EafzQ4BEmyK9cAGn8PW/view?usp=sharing

Tell me your opinion and have fun :)

**Comment by Russianstory** [comment]
@FAPLZ Good evening! =))))))))))) BRO )) Do your fortresses only come with you JSON ? Or can I keep mine?


And also, here are my personal fortresses that you improve, is there any AI and AIC on them so that it goes very well with them? It turns out just like that - we have strong fortresses with your refinement, and AI and AIC will be either standard or slightly enhanced?

Thank you very much!) I will install and play with them =) And just throw them into the folder for the game?

**Comment by FAPLZ** [comment]
@Russianstory good evening too bratan :D

My AIV files works with my own aic but it should also work with vanilla (but not so good) and the other aics: i dont know. i dont tested it yet.
And yes for the new AIV files i recommend ne aic files but it should work fine with the vanilla files. and here i also dont know if other aic files work.

Until now i only tested the vanilla and my aic files, sorry for that. maybe in the future i can tell you more ;)

**Comment by Russianstory** [comment]
@FAPLZ OK I will then do so download your fortresses and AIC porridges (both links). Are my fortresses still under development? =)

**Comment by FAPLZ** [comment]
@Russianstory

of course your castles will be ready soon. i tell you when i am finished

**Comment by Russianstory** [comment]
@FAPLZ Hi bro! GOOOOG VERY GOOOD )))) THX VERY MUCH 
Great job! Thank you!)) then I’ll sit down to watch and test it all!)

But to be honest, I can’t even imagine how else to improve the layout of the fortresses?

I am always in favor of having a lot of wolf stakes and pharmacies. This greatly enhances the defensive potential of the fortress.

**Comment by Russianstory** [comment]
Hello @FAPLZ !!! I started testing them =) Let's see what they cost now!))) And tell me, please, what exactly did you change/add? What should I pay close attention to?

And further.
And that little archive with fortresses, which I also threw (there were few fortresses there), is it also ready or not? And then I started to get confused =)

**Comment by Russianstory** [comment]
@FAPLZ 
Unfortunately, I see that the Rat has pikemen in the army. Can you please not make pikemen, but reorient the workshops to the production of spears, and replace the iron armor workshops with 50/50 workshops for spears and bow workshops? And I have not yet noticed that the wolf stakes would be outside the Fortress under the walls.

**Comment by Russianstory** [comment]
Upd. 
WHEN PLAYING WITH SNAKE, THE GAME CRASHES WITHOUT EXPLANATION OF THE REASON. SIMPLY CLIMB TO THE DESKTOP. I DON'T UNDERSTAND WHY

**Comment by Russianstory** [comment]
Upd
And the PIG makes pikemen and euro archers instead of crossbowmen. Can I please ask you to remove the Pike workshops and instead increase the number of leather, crossbow and mace workshops.

**Comment by Russianstory** [comment]
It was when playing with Pigs that the game crashed twice and crashed into a black screen. Hm strange

**Comment by Russianstory** [comment]
The same situation with Pigs, but on a different map

**Comment by Russianstory** [comment]
Wolf - same error

**Comment by FAPLZ** [comment]
@Russianstory 

Hello my Friend

i had the same problems soemtimes when i was playing especially against wolf. in the editor i removed some spikes in the castle and then the castle works and the game doesnt crash. i think the problem is, that some spikes are blocking the way of some workes or something similar.

with the pig, i can remove the workshops. but then maybe the economy is struggling. But the main problem is not the workshops. the problem is the AIC-file of the Pig you use, which said, that the Pig should use pikeman in one way or another.
When you use the vanilla AI then it shouldnt build pikeman.
(The reason why there are pikeman workshops is, that the castle layout was one of my created castles for my own AIC, where the pig uses Spearman). I will send you the new castles soon.


i am busy in the last time, but i try to do my best to fix it

**Comment by Russianstory** [comment]
SAladin - same problem ((

**Comment by Russianstory** [comment]
Hi my friend! =)

**Comment by FAPLZ** [comment]
Hello @Russianstory i will see in the next time what i can do. now i am ready and have time to do some stronghold stuff

**Comment by Heroesflorian** [comment]
So... am I correct that this Issue-thread here running since 2020 has a gazillion messages mentioning a bunch of different things, all of them related to a set of AIVs, and that those AIVs currently do not even come bundled with the UCP, are not from the UCP team or otherwise related directly to the UCP? AIVs that even have their own separate git repository ([FAPLZ AIVs](https://github.com/FAPLZ/AIV-files-for-Stronghold-Crusader)), if I understand correctly? 

I would strongly suggest to create separate, individual issue posts for dealing with separate, individual issues, instead of throwing all into one bucket that makes it impossible to find stuff later. 
**But more importantly**... those issues belong there: [FAPLZ AIVs: Issues](https://github.com/FAPLZ/AIV-files-for-Stronghold-Crusader/issues), on the issues section of the AIVs' repository, and not here onto the UCP repository. 

The only relevant thing for here is mentioning that this AIV set exists and is set up in a UCP-compatible way.

**Comment by Russianstory** [comment]
@FAPLZ greetings sir! Whats new ? =)

**Comment by FAPLZ** [comment]
@Russianstory 
Hello my friend. i am looking forward to fix the problems. we have to continue our conversation here: https://github.com/FAPLZ/AIV-files-for-Stronghold-Crusader/issues/1

**Comment by FAPLZ** [comment]
@Russianstory 
Hello my friend. i am looking forward to fix the problems. we have to continue our conversation here: https://github.com/FAPLZ/AIV-files-for-Stronghold-Crusader/issues/1
