### ISSUE TITLE
Faster and easier siege equipment building

### ISSUE THREAD

**Issue by LordUvin** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#866]
Idea is to select shield somehow, so it is not necessary to select again. 
For example, 

- first click on shield with right mouse button, 
- then just click (LMB) in random locations on map and engineers are going to make shields. 

There could be many ways to do it. Maybe selecting desired siege equipment by numbers (1-6).

**Comment by gynt** [comment]
3. keeping the "build shield" selection active until right mouse button.

**Comment by LordUvin** [comment]
> Alternative: keeping the "build shield" selection active until right mouse button.

Good idea!

**Comment by gynt** [comment]
Hmm I just checked this, but already in the game, the shield building mode stays active if you first have a bunch of engineers selected.

Do you mean something different?

**Comment by LordUvin** [comment]
> Hmm I just checked this, but already in the game, the shield building mode stays active if you first have a bunch of engineers selected.
> 
> Do you mean something different?

No worries. All is working. Tnx for commenting. I will close this issue.

**Comment by LeSpec** [comment]
> Hmm I just checked this, but already in the game, the shield building mode stays active if you first have a bunch of engineers selected.
> 
> Do you mean something different?

@gynt you really don't play the game? 🤣

**Comment by gynt** [comment]
> > Hmm I just checked this, but already in the game, the shield building mode stays active if you first have a bunch of engineers selected.
> > Do you mean something different?
> 
> @gynt you really don't play the game? 🤣

*BUSTED*
