### ISSUE TITLE
Game speed error

### ISSUE THREAD

**Issue by PodzemniyBomj** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#882]
Tried to install UCP and got this:
![Screenshot_1](https://user-images.githubusercontent.com/88278568/127773322-c6f476d6-36a2-4bcb-a096-04dd8038deee.jpg)
Due to this error I can't change game speed more than 90. Everything else works fine. I'm using Steam version of Crusader. Is there any way to fix this?

**Comment by GRhin** [comment]
This is usually caused by a language issue. Is your game installed as English?

**Comment by PodzemniyBomj** [comment]
Han, it's Russian

**Comment by PodzemniyBomj** [comment]
No, it's Russian

**Comment by GRhin** [comment]
Unfortunately Russian is one of the languages that don't play nicely with the ucp. Hopefully a future version will resolve this, but for now if you want to use the speed feature you will need to install the English version.
Basically any language that doesn't use the latin alphabet has this issue (Russian and Chinese for example). I believe player color also won't work.

**Comment by PodzemniyBomj** [comment]
Yeah, on English version everything works good, thanks for the help.
